### ISSUE TITLE
accordion and tabs spit out code with ruby 1.9

### ISSUE THREAD

**Issue by kaiiserni** [CodeOfficer/jquery-ui-rails-helpers#1]
I upgraded to ruby 1.9. 
When I use accordion and tabs, I get 
["
at the beginning of the ellement, the content is screwed up as well with \n and slashes.
in between the elements i get ","
and at the end ]"

is this a known issue? 
Can you please look into this as the plugin really comes in handy for me!

thanks

**Comment by kaiiserni** [comment]
fixed it by adding .join to the array , apparently this is a change in to_s handling by ruby 1.9:

def render  
      content_tag :div, { :id => :accordions }.merge( @options ) do
        @accordions.collect do |accordion|

```
      accordion_head(accordion) + accordion_body(accordion)

    end
    .join
  end
end 
```

Is it possible to verify it and update the code?

thanks

**Comment by CodeOfficer** [comment]
I will get on this asap. Thanks for the heads up.

**Comment by CodeOfficer** [comment]
fixed a ruby 1.9 issue for Array.to_s. closed by 9a140a097d98cfd1d9d40d547cc3bf7f85649344

**Comment by kaiiserni** [comment]
Hi CodeOfficer,

thanks, thats fixed really fast ;-)
I have noticed the same issue in the tabs helper as well, 
actually the .join needs to be added in all places where you do a .collect:

@tabs.collect do |tab|
          content_tag( :li, link_to( content_tag( :span, tab[1] ), "##{tab[0]}" ) )
        end
        .join

and

@tabs.collect do |tab| 
        content_tag( :div, capture( &tab[3] ), tab[2].merge( :id => tab[0] ) ) 
      end.join

thanks

**Comment by CodeOfficer** [comment]
Got it! Sorry, I tried to throw that in without having 1.9 installed to test on. Horrible of me I know.

**Comment by kaiiserni** [comment]
thanks :-)
