### ISSUE TITLE
tabs_for renders escaped bodies on ror 2.3.8

### ISSUE THREAD

**Issue by altamic** [CodeOfficer/jquery-ui-rails-helpers#3]
Hi Russell,
the problem is resolved here:
http://github.com/michelangelo-altamore/jquery-ui-rails-helpers/tree/content_tag-takes-an-array
I've successfully tested the patch on a 2.3.5 app for backward compatibility.

**Comment by CodeOfficer** [comment]
thanks again!

**Comment by CodeOfficer** [comment]
I've just gemified the helpers and added actual tests which run fine for ruby 1.8 and 1.9 along with rails 3.x
