### ISSUE TITLE
Adding itnit.rb for easier plugin loading

### ISSUE THREAD

**Issue by bacrossland** [CodeOfficer/jquery-ui-rails-helpers#4]
Just a suggestion for easier plugin loading and management. You might want to create in the plugin root directory init.rb and rails/init.rb.

init.rb has the following:
require 'rails/init.rb'

rails/init.rb has the following:
require "#{RAILS_ROOT}/vendor/plugins/jquery-ui-rails-helpers/helpers/tabs_helper.rb"
require "#{RAILS_ROOT}/vendor/plugins/jquery-ui-rails-helpers/helpers/accordions_helper.rb"

ActionView::Base.send :include, TabsHelper
ActionView::Base.send :include, AccordionsHelper

I did this on my 2.3.8 application after upgrading from earlier version of this plugin.

**Comment by CodeOfficer** [comment]
Agreed, It should really be gemified. I have written a number of other UI helpers as well that I want to bundle with it. I'm glad you found it useful. I'll try to squeeze in some time next week to gem up the helpers and add my others :)

**Comment by CodeOfficer** [comment]
Took me forever to get around to, but I've just gemified the helpers and added tests to support ruby 1.8/1.9 with rails 3.0. Didn't see the need to add 2.3.8 support.
