### ISSUE TITLE
Broken in Rails 3

### ISSUE THREAD

**Issue by metasoarous** [CodeOfficer/jquery-ui-rails-helpers#5]
The accordions helper is broken in Rails 3 now. It ends up rendering the accordion twice. I'll look into this a bit, but do you have plans of updating?

Chris

**Comment by metasoarous** [comment]
Easy as cake - just replace 

```
concat accordions_html
```

in the definition of accordions_for with

```
accordions_html
```

The concat method was putting the content down, but since the method was also returning the content, it was inserting that as well. 

Cheers

Chris

**Comment by CodeOfficer** [comment]
I've been meaning to gemify these helpers. I'll update this code for RubyConf next week, probably just for Rails 3. Thanks for the heads up!

**Comment by metasoarous** [comment]
Sure thing

**Comment by metasoarous** [comment]
Just thought I would let you know -  I'm going through the tabs_helper now and finding that it seems to be a little trickier than just taking out concat. It seems to be escpaing the content divs, and I'm not sure why yet. If I figure it out, I'll let you know. If you manage to get it first though, do let me know when you get a chance.

**Comment by metasoarous** [comment]
Alright - I'm not too sure why this used to work and doesn't now - it may be a rails bug. I found Yehuda's blog post (http://yehudakatz.com/2010/02/01/safebuffers-and-rails-3-0/) on safe buffers and saw down in the section called "Safe Buffer" that an instance of ActiveRecord::SafeBuffer inherits from String and modifies the way that string addition (and concatenation, <<) work, so that if the second string is not wrapped as being safe then it is escaped. This was after boiling everything down to realize that when I replaced "render_tabs + render_bodies" with just render_bodies, the bodies rendered just fine. When I left in the addition, it escaped the divs. Strange, since that content came from a call to content_tag - you would figure that would create a safe string. But, I went ahead and tried calling html_safe (which wraps the string in a SafeBuffer instance) on the return value of render_bodies and now it works! The addition went through successfully without escaping the second string. 

So - for the tabs helper, concat needs to be removed and html_safe has to be added to render_blocks as described and as below

```
    def render
        content_tag( :div, (render_tabs + render_bodies.html_safe), { :id => :tabs }.merge( @options ) )
    end
```

Although, now that it is looking a bit longer, I'm liking

```
    def render
        content_tag( :div, { :id => :tabs }.merge( @options ) ) do
            (render_tabs + render_bodies.html_safe)
        end
    end
```

What do you think? Am I missing something or does this seem to be a bug in rails?

Some other thoughts, now that rails has stylized itself so that any block which returns printed content should use (by way of example)

```
= form_for @post ...
```

instead of 

```
- form_for @post ...
```

it might be a good call to stylize these helpers similarly, so that "= tab.create..." is used instead of "- tab.create...". For right now, what works works, but it's something to consider.

Cheers

**Comment by CodeOfficer** [comment]
I've just gemified the helpers and added tests to support ruby 1.8/1.9 and rails 3.x

**Comment by metasoarous** [comment]
Awesome!
